<?php

declare(strict_types=1);

namespace AirSlate\Releaser\Commands\PullRequests\DropAutoInstall;

use AirSlate\Releaser\Builder;
use AirSlate\Releaser\Exceptions\FileNotFoundInRepositoryException;
use AirSlate\Releaser\Processors\JsonProcessor;
use Fluffy\GithubClient\Client as GithubClient;
use ReflectionException;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class DropAutoInstallCommand extends Command
{
    /**
     * @return void
     */
    protected function configure(): void
    {
        $this
            ->setName('pr:auto-install')
            ->setDescription('Drop auto-install attribute from addon scheme');
    }

    /**
     * @param InputInterface $input
     * @param OutputInterface $output
     * @return void
     * @throws ReflectionException
     */
    protected function execute(InputInterface $input, OutputInterface $output): void
    {
        $output->writeln('<info>Remove auto_install attribute.</info>');
        $client = new GithubClient([
            'owner' => getenv('OWNER'),
            'token' => getenv('GITHUB_OAUTH_TOKEN'),
        ]);

        $this->config = require_once './config/addons.php';
        $addons = $this->config['addons'] ?? [];

        foreach ($addons as $addon) {
            try {
                (new Builder($client, $addon))
                    ->verify(function (JsonProcessor $addonScheme) {
                        return $addonScheme
                            ->take('docker/config/addon/delete/addon.json')
                            ->isset('data.attributes.auto_install');
                    }, function () use ($output, $addon) {
                        $output->writeln("<info>{$addon} already without auto_install!</info>");
                    })
                    ->setOutput($output)
                    ->notify("Updating...")
                    ->forTask('AAD-532')
                    ->from('develop')
                    ->branch('drop-autoinstall-attribute')
                    ->step(function (JsonProcessor $addonScheme) {
                        return $addonScheme
                            ->take('docker/config/addon/delete/addon.json')
                            ->unsetKey('data.attributes.auto_install');
                    })
                    ->commit('Drop auto_install attribute from scheme')
                    ->push()
                    ->makePR('Drop auto_install attribute from scheme', 'Autogenerated PR');
            } catch (FileNotFoundInRepositoryException $e) {
                $output->writeln("<comment>{$addon}: File not found!</comment>");
            }
        }
    }
}
