<?php

declare(strict_types=1);

namespace AirSlate\Releaser\Commands\PullRequests\DropAutoInstall;

use AirSlate\Releaser\Builder;
use AirSlate\Releaser\Processors\JsonProcessor;
use Fluffy\GithubClient\Client as GithubClient;
use ReflectionException;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class DropAutoInstallCommand extends Command
{
    /**
     * @return void
     */
    protected function configure(): void
    {
        $this
            ->setName('pr:auto-install')
            ->setDescription('Drop auto-install attribute from addon scheme');
    }

    /**
     * @param InputInterface $input
     * @param OutputInterface $output
     * @return void
     * @throws ReflectionException
     */
    protected function execute(InputInterface $input, OutputInterface $output): void
    {
        $output->writeln('<info>Remove auto_install attribute.</info>');
        $client = new GithubClient([
            'owner' => getenv('OWNER'),
            'token' => getenv('GITHUB_OAUTH_TOKEN'),
        ]);

        foreach (['tags-addon'] as $addon) {
            (new Builder($client, 'airslateinc', $addon))
                ->verify(function (JsonProcessor $addonScheme) {
                    return $addonScheme
                        ->take('docker/config/addon/create/addon.json')
                        ->isset('data.attributes.auto_install');
                }, $output, $addon)
                ->forTask('AAD-532')
                ->from('develop')
                ->branch('drop-auto-install-attribute')
                ->step(function (JsonProcessor $addonScheme) {
                    return $addonScheme
                        ->take('docker/config/addon/create/addon.json')
                        ->unsetKey('data.attributes.auto_install');
                })
                ->commit('Drop auto_install attribute from scheme')
                ->push()
                ->makePR('Drop auto_install attribute from scheme', 'Autogenerated PR');
        }
    }
}
