<?php
declare(strict_types=1);

require_once __DIR__ . '/vendor/autoload.php';

$dotenv = Dotenv\Dotenv::create(__DIR__);
$dotenv->load();

use AirSlate\Releaser\Builder;
use AirSlate\Releaser\FileProcessor;
use Fluffy\GithubClient\Client;

$client = new Client([
    'owner' => getenv('OWNER'),
    'token' => getenv('GITHUB_OAUTH_TOKEN'),
]);

/*$addons = [
    'prefill-from-source-addons',
    'audit-trail-addon',
    'change-order-addon',
    'document-prefill-addon',
    'dropdown-options-prefill-addon',
    'google-calendar-addon',
    'google-spreadsheets-duplex-addon',
    'google-spreadsheets-postfinish-addon',
    'google-spreadsheets-watcher-addon',
    'jira-addon',
    'lock-slate-bot',
    'notification-addon',
    'export-to-source-addons',
    'packet-delete-addon',
    'recipient-to-role-addon',
    'revoke-access-addon',
    'roles-users-management-addon',
    'send-slate-addon',
    'set-packet-name-addon',
    'slack-notifier-addon',
    'slate-prefill-addon',
    'smartsheet-export-addon',
    'sms-notifier-addon',
    'tags-addon',
    'webhook-addon',
    'weekly-reminder-addon',
];*/

$addons = [
    'prefill-from-source-addons',
];

foreach ($addons as $addon) {
    (new Builder($client, 'airslateinc', $addon))
        ->from('develop')
        ->branch('test-migration')
        ->step(function (FileProcessor $file) {
            return $file
                ->create('docker/provision/migration.sh', '#!/usr/bin/env bash

bash /app/docker/provision/consul.sh --once
ENV_FILE="/app/.env"

if [ -f $ENV_FILE ]; then
    printf "File $ENV_FILE found! Starting migration.\n"
    cd /app
    /usr/bin/php artisan migrate --force
else
    printf "File $ENV_FILE not found!\n"
fi
');
        })
        ->step(function (FileProcessor $file) {
            return $file
                ->take('docker/provision/after-consul.sh')
                ->replace("/usr/bin/php artisan migrate --force\n", '');
        })
        ->commit('[test] Test add file')
        ->push()
        ->makePR('[test] Test add file', 'Autogenerated PR');
}
