#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$dotenv = Dotenv\Dotenv::create(__DIR__);
$dotenv->load();

$app = new Symfony\Component\Console\Application('Lets rock and develop addons', '0.0.1');
$app->add(new AirSlate\Releaser\Commands\PatchCircleCIEnvCommand());
$app->add(new AirSlate\Releaser\Commands\PatchGithubEnvCommand());
$app->add(new AirSlate\Releaser\Commands\AddonFetchCommand());
$app->add(new AirSlate\Releaser\Commands\ConstantsFetchCommand());
$app->add(new AirSlate\Releaser\Commands\ReleaseDone());
$app->add(new AirSlate\Releaser\Commands\PullRequests\AddCircleCI\AddCircleCICommand());
$app->add(new AirSlate\Releaser\Commands\PullRequests\DropAutoInstall\DropAutoInstallCommand());
$app->add(new AirSlate\Releaser\Commands\PatchLabelsCommand());
$app->add(new AirSlate\Releaser\Commands\PullRequests\EnablePHPCS\EnablePHPCS());
$app->add(new AirSlate\Releaser\Commands\PullRequests\ReplaceTags\ReplaceTags());
$app->add(new AirSlate\Releaser\Commands\PullRequests\EnablePHPMD\EnablePHPMD());
$app->add(new AirSlate\Releaser\Commands\UpdateBaseDockerImageCommand());
$app->add(new AirSlate\Releaser\Commands\CheckVersions());
$app->add(new AirSlate\Releaser\Commands\CheckDependencies());
$app->add(new AirSlate\Releaser\Commands\UpdateDependencies());
$app->add(new AirSlate\Releaser\Commands\CheckWebConfig());
$app->add(new AirSlate\Releaser\Commands\PullRequests\NewRegistration\NewRegistration());
$app->add(new AirSlate\Releaser\Commands\PullRequests\AddDockerIgnore\AddDockerIgnore());
$app->add(new AirSlate\Releaser\Commands\PullRequests\FixReg\FixRegCommand());
$app->add(new AirSlate\Releaser\Commands\PullRequests\AddCoverageMetrics\AddCoverageMetrics());
$app->run();
