<?php

declare(strict_types=1);

namespace AirSlate\Releaser\Commands;

use AirSlate\Releaser\Builder;
use AirSlate\Releaser\Docker\DockerContainer;
use AirSlate\Releaser\Docker\DockerContainerInstance;
use AirSlate\Releaser\Processors\ComposerProcessor;
use Spatie\Docker\Exceptions\CouldNotStartDockerContainer;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class UpdateDependencies extends AddonsCommand
{
    /** @var DockerContainerInstance */
    private $container;

    /**
     * @return void
     */
    protected function configure(): void
    {
        $this
            ->setName('deps:update')
            ->setDescription('Update dependencies');
            //->addArgument('package', InputArgument::REQUIRED, 'Package for check.')
            //->addArgument('version', InputArgument::REQUIRED, 'Version for check.');
    }

    /**
     * @param InputInterface $input
     * @param OutputInterface $output
     * @throws CouldNotStartDockerContainer
     */
    protected function beforeCommand(InputInterface $input, OutputInterface $output)
    {
        parent::beforeCommand($input, $output);
        $this->container = DockerContainer::create('pdffiller/php72-ubuntu16:v1.3.2')
            ->start();
        $output->writeln('<info>Update addon dependency.</info>');
    }

    /**
     * @param string $addon
     * @param InputInterface $input
     * @param OutputInterface $output
     * @throws \ReflectionException
     */
    protected function step(string $addon, InputInterface $input, OutputInterface $output)
    {
        $output->writeln('Started ' . $addon);
        (new Builder($this->client, $addon))
            ->setOutput($output)
            ->forTask('AAD-1183')
            ->from('develop')
            ->step(function (ComposerProcessor $schema) use ($input, $output, $addon) {
                $schema->setContainerInstance($this->container);
                return $schema->ensure(
                    'airslate/addon-php-utils',
                    '^12.3.9',
                    $this->config['github_ouath_token']
                );
            })
            ->branch('php-utils-update')
            ->commit('Update the addon-php-utils to change the error tag')
            ->push()
            ->makePR('Update the addon-php-utils to change the error tag', 'Autogenerated PR');
        $output->writeln('Finished ' . $addon);
    }

    public function afterCommand(InputInterface $input, OutputInterface $output)
    {
        parent::afterCommand($input, $output);
        $this->container->stop();
    }
}
