<?php

declare(strict_types=1);

namespace AirSlate\Releaser\Commands;

use AirSlate\Releaser\Builder;
use AirSlate\Releaser\Processors\FileProcessor;
use Fluffy\GithubClient\Client as GithubClient;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class UpdateBaseDockerImageCommand extends AddonsCommand
{
    /** @var array */
    private $config;

    /** @var GithubClient */
    protected $client;

    /**
     * @return void
     */
    protected function configure(): void
    {
        $this
            ->setName('docker:update-base')
            ->setDescription('Update base Docker image');
    }

    /**
     * @param InputInterface $input
     * @param OutputInterface $output
     */
    protected function beforeCommand(InputInterface $input, OutputInterface $output)
    {
        $output->writeln('<comment>Docker base image updating...</comment>');
    }

    /**
     * @param InputInterface $input
     * @param OutputInterface $output
     * @return void
     * @throws \ReflectionException
     */
    protected function step(string $addon, InputInterface $input, OutputInterface $output): void
    {
        (new Builder($this->client, $addon))
            ->setOutput($output)
            ->forTask('docker')
            ->from('develop')
            ->step(function (FileProcessor $dockerfile) {
                return $dockerfile
                    ->take('Dockerfile')
                    ->regexReplace(
                        '/(pdffiller\/php72-ubuntu16:v)\d+\.\d+\.\d+/',
                        '${1}1.3.2'
                    );
            })
            ->branch('update-docker-image')
            ->commit('Update base docker image')
            ->push()
            ->makePR('Update base docker image', 'Autogenerated PR')
            ->notify('Updated!');
    }

    /**
     * @param string $addon
     * @param InputInterface $input
     * @param OutputInterface $output
     */
    protected function nothingToCommit(string $addon, InputInterface $input, OutputInterface $output)
    {
        $output->writeln("<comment>Nothing to commit in {$addon}.</comment>");
    }
}
