<?php

return [
    'addons' => [
        'webhook-addon',
        'notification-addon',
        'jira-addon',
        'tags-addon',
        'slack-notifier-addon',
        'document-prefill-addon',
        'prefill-from-source-addons',
        'quickbooks-invoice-addon',
        'export-to-source-addons',
        'google-spreadsheets-duplex-addon',
        'mailchimp-send-campaign-addon',
        'google-spreadsheets-postfinish-addon',
        'slate-prefill-addon',
        'set-signature-types-addon',
        'set-packet-name-addon',
        'mailchimp-add-recipient-addon',
        'hide-fields-values-addon',
        'roles-users-management-addon',
        'create-slate-reminder-addon',
        'watcher-from-source-addons',
        'create-slate-addon',
        'google-cloud-print-addon',
        'smartsheet-export-addon',
        'packet-delete-addon',
        'role-reminder-addon',
        'open-as-role-addon',
        'dropdown-options-prefill-addon',
        'audit-trail-addon',
        'google-calendar-addon',
        'sms-notifier-addon',
        'google-spreadsheets-watcher-addon',
        'custom-field-value-addon',
        'create-slate-another-flow-addon',
    ],
    'labels' => [
        [
            'name' => 'approved',
            'color' => '008672',
            'description' => 'Approved by applications and platform teams',
        ],
        [
            'name' => 'waiting for platform review',
            'color' => '1d76db',
            'description' => 'Approved by applications team and waiting for platform team',
        ]
    ],
];
